export const APP_NAVIGATION_MAIN = 'MAIN';
export const APP_NAVIGATION_LOST_REPORT_STACK = 'LOST_REPORT_STACK';
export const APP_NAVIGATION_CATCH_REPORT_STACK = 'CATCH_REPORT_STACK';
export const APP_NAVIGATION_REPORT_MODAL = 'REPORT_MODAL';
export const APP_NAVIGATION_ABANDONED_MODAL = 'ABANDONED_MODAL';
export const APP_NAVIGATION_LOST_REPORT_LIST = 'LOST_REPORT_LIST';
export const APP_NAVIGATION_CATCH_REPORT_LIST = 'CATCH_REPORT_LIST';
export const APP_NAVIGATION_REPORT_MAP = 'REPORT_MAP';
export const APP_NAVIGATION_LOST_REPORT_DETAIL = 'LOST_REPORT_DETAIL';
export const APP_NAVIGATION_CATCH_REPORT_DETAIL = 'CATCH_REPORT_DETAIL';
export const APP_NAVIGATION_PET_DATA_REPORT_DETAIL = 'PET_DATA_REPORT_DETAIL';

export const MAIN_NAVIGATION_HOME = '홈';
export const MAIN_NAVIGATION_MAP = '지역';
export const MAIN_NAVIGATION_REGISTER = '등록';
export const MAIN_NAVIGATION_DETECTIVE = '의뢰';
export const MAIN_NAVIGATION_MORE = '더보기';

export const LOST_REPORT_STEP1 = 'LOST_REPORT_STEP1';
export const LOST_REPORT_STEP2 = 'LOST_REPORT_STEP2';
export const LOST_REPORT_STEP3 = 'LOST_REPORT_STEP3';
export const LOST_REPORT_RESULT = 'LOST_REPORT_RESULT';
export const LOST_REPORT_COMPLETE = 'LOST_REPORT_COMPLETE';

export const CATCH_REPORT_STEP1 = 'CATCH_REPORT_STEP1';
export const CATCH_REPORT_STEP2 = 'CATCH_REPORT_STEP2';
export const CATCH_REPORT_STEP3 = 'CATCH_REPORT_STEP3';
export const CATCH_REPORT_RESULT = 'CATCH_REPORT_RESULT';
