export const CATEGORY_LIST = [
  {
    name: '전체',
    value: 'all',
  },
  {
    name: '강아지',
    value: 'dog',
  },
  {
    name: '고양이',
    value: 'cat',
  },
  {
    name: '기타',
    value: 'etc',
  },
];

export const BREED_LIST = [
  { label: '모르겠음', value: 'any' },
  { label: 'Chihuahua', value: 'Chihuahua' },
  { label: 'Japanese spaniel', value: 'Japanese spaniel' },
  { label: 'Maltese dog', value: 'Maltese dog' },
  { label: 'Pekinese', value: 'Pekinese' },
  { label: 'Shih Tzu', value: 'Shih Tzu' },
  { label: 'Blenheim spaniel', value: 'Blenheim spaniel' },
  { label: 'papillon', value: 'papillon' },
  { label: 'toy terrier', value: 'toy terrier' },
  { label: 'Rhodesian ridgeback', value: 'Rhodesian ridgeback' },
  { label: 'Afghan hound', value: 'Afghan hound' },
  { label: 'basset', value: 'basset' },
  { label: 'beagle', value: 'beagle' },
  { label: 'bloodhound', value: 'bloodhound' },
  { label: 'bluetick', value: 'bluetick' },
  { label: 'black and tan coonhound', value: 'black and tan coonhound' },
  { label: 'Walker hound', value: 'Walker hound' },
  { label: 'English foxhound', value: 'English foxhound' },
  { label: 'redbone', value: 'redbone' },
  { label: 'borzoi', value: 'borzoi' },
  { label: 'Irish wolfhound', value: 'Irish wolfhound' },
  { label: 'Italian greyhound', value: 'Italian greyhound' },
  { label: 'whippet', value: 'whippet' },
  { label: 'Ibizan hound', value: 'Ibizan hound' },
  { label: 'Norwegian elkhound', value: 'Norwegian elkhound' },
  { label: 'otterhound', value: 'otterhound' },
  { label: 'Saluki', value: 'Saluki' },
  { label: 'Scottish deerhound', value: 'Scottish deerhound' },
  { label: 'Weimaraner', value: 'Weimaraner' },
  { label: 'Staffordshire bullterrier', value: 'Staffordshire bullterrier' },
  {
    label: 'American Staffordshire terrier',
    value: 'American Staffordshire terrier',
  },
  { label: 'Bedlington terrier', value: 'Bedlington terrier' },
  { label: 'Border terrier', value: 'Border terrier' },
  { label: 'Kerry blue terrier', value: 'Kerry blue terrier' },
  { label: 'Irish terrier', value: 'Irish terrier' },
  { label: 'Norfolk terrier', value: 'Norfolk terrier' },
  { label: 'Norwich terrier', value: 'Norwich terrier' },
  { label: 'Yorkshire terrier', value: 'Yorkshire terrier' },
  { label: 'wire haired fox terrier', value: 'wire haired fox terrier' },
  { label: 'Lakeland terrier', value: 'Lakeland terrier' },
  { label: 'Sealyham terrier', value: 'Sealyham terrier' },
  { label: 'Airedale', value: 'Airedale' },
  { label: 'cairn', value: 'cairn' },
  { label: 'Australian terrier', value: 'Australian terrier' },
  { label: 'Dandie Dinmont', value: 'Dandie Dinmont' },
  { label: 'Boston bull', value: 'Boston bull' },
  { label: 'miniature schnauzer', value: 'miniature schnauzer' },
  { label: 'giant schnauzer', value: 'giant schnauzer' },
  { label: 'standard schnauzer', value: 'standard schnauzer' },
  { label: 'Scotch terrier', value: 'Scotch terrier' },
  { label: 'Tibetan terrier', value: 'Tibetan terrier' },
  { label: 'silky terrier', value: 'silky terrier' },
  {
    label: 'soft coated wheaten terrier',
    value: 'soft coated wheaten terrier',
  },
  {
    label: 'West Highland white terrier',
    value: 'West Highland white terrier',
  },
  { label: 'Lhasa', value: 'Lhasa' },
  { label: 'flat coated retriever', value: 'flat coated retriever' },
  { label: 'curly coated retriever', value: 'curly coated retriever' },
  { label: '골든리트리버', value: '골든리트리버' },
  { label: 'Labrador retriever', value: 'Labrador retriever' },
  { label: 'Chesapeake Bay retriever', value: 'Chesapeake Bay retriever' },
  {
    label: 'German short haired pointer',
    value: 'German short haired pointer',
  },
  { label: 'vizsla', value: 'vizsla' },
  { label: 'English setter', value: 'English setter' },
  { label: 'Irish setter', value: 'Irish setter' },
  { label: 'Gordon setter', value: 'Gordon setter' },
  { label: 'Brittany spaniel', value: 'Brittany spaniel' },
  { label: 'clumber', value: 'clumber' },
  { label: 'English springer', value: 'English springer' },
  { label: 'Welsh springer spaniel', value: 'Welsh springer spaniel' },
  { label: 'cocker spaniel', value: 'cocker spaniel' },
  { label: 'Sussex spaniel', value: 'Sussex spaniel' },
  { label: 'Irish water spaniel', value: 'Irish water spaniel' },
  { label: 'kuvasz', value: 'kuvasz' },
  { label: 'schipperke', value: 'schipperke' },
  { label: 'groenendael', value: 'groenendael' },
  { label: 'malinois', value: 'malinois' },
  { label: 'briard', value: 'briard' },
  { label: 'kelpie', value: 'kelpie' },
  { label: 'komondor', value: 'komondor' },
  { label: 'Old English sheepdog', value: 'Old English sheepdog' },
  { label: 'Shetland sheepdog', value: 'Shetland sheepdog' },
  { label: 'collie', value: 'collie' },
  { label: 'Border collie', value: 'Border collie' },
  { label: 'Bouvier des Flandres', value: 'Bouvier des Flandres' },
  { label: 'Rottweiler', value: 'Rottweiler' },
  { label: 'German shepherd', value: 'German shepherd' },
  { label: 'Doberman', value: 'Doberman' },
  { label: 'miniature pinscher', value: 'miniature pinscher' },
  { label: 'Greater Swiss Mountain dog', value: 'Greater Swiss Mountain dog' },
  { label: 'Bernese mountain dog', value: 'Bernese mountain dog' },
  { label: 'Appenzeller', value: 'Appenzeller' },
  { label: 'EntleBucher', value: 'EntleBucher' },
  { label: 'boxer', value: 'boxer' },
  { label: 'bull mastiff', value: 'bull mastiff' },
  { label: 'Tibetan mastiff', value: 'Tibetan mastiff' },
  { label: 'French bulldog', value: 'French bulldog' },
  { label: 'Great Dane', value: 'Great Dane' },
  { label: 'Saint Bernard', value: 'Saint Bernard' },
  { label: 'Eskimo dog', value: 'Eskimo dog' },
  { label: 'malamute', value: 'malamute' },
  { label: 'Siberian husky', value: 'Siberian husky' },
  { label: 'affenpinscher', value: 'affenpinscher' },
  { label: 'basenji', value: 'basenji' },
  { label: 'pug', value: 'pug' },
  { label: 'Leonberg', value: 'Leonberg' },
  { label: 'Newfoundland', value: 'Newfoundland' },
  { label: 'Great Pyrenees', value: 'Great Pyrenees' },
  { label: 'Samoyed', value: 'Samoyed' },
  { label: 'Pomeranian', value: 'Pomeranian' },
  { label: 'chow', value: 'chow' },
  { label: 'keeshond', value: 'keeshond' },
  { label: 'Brabancon griffon', value: 'Brabancon griffon' },
  { label: 'Pembroke', value: 'Pembroke' },
  { label: 'Cardigan', value: 'Cardigan' },
  { label: 'toy poodle', value: 'toy poodle' },
  { label: 'miniature poodle', value: 'miniature poodle' },
  { label: 'standard poodle', value: 'standard poodle' },
  { label: 'Mexican hairless', value: 'Mexican hairless' },
  { label: 'dingo', value: 'dingo' },
  { label: 'dhole', value: 'dhole' },
  { label: 'African hunting dog', value: 'African hunting dog' },
];

export const MAX_IMAGE = 10;
