export const CATEGORY_LIST = [
  {
    name: '전체',
    value: 'all',
  },
  {
    name: '강아지',
    value: 'dog',
  },
  {
    name: '고양이',
    value: 'cat',
  },
  {
    name: '기타',
    value: 'etc',
  },
];

export const BREED_LIST = [
  { label: '모르겠음', value: '모르겠음' },
  { label: '고든 세터', value: '고든 세터' },
  { label: '골든리트리버', value: '골든리트리버' },
  {
    label: '그레이터 스위스 마운틴 도그',
    value: '그레이터 스위스 마운틴 도그',
  },
  { label: '그레이트 데인', value: '그레이트 데인' },
  { label: '그레이트 피레니즈', value: '그레이트 피레니즈' },
  { label: '그루넨달', value: '그루넨달' },
  { label: '노르웨이언 엘크하운드', value: '노르웨이언 엘크하운드' },
  { label: '노리치 테리어', value: '노리치 테리어' },
  { label: '노퍽 테리어', value: '노퍽 테리어' },
  { label: '뉴펀들랜드', value: '뉴펀들랜드' },
  { label: '댄디 딘몬트 테리어', value: '댄디 딘몬트 테리어' },
  { label: '도베르만 핀셔', value: '도베르만 핀셔' },
  { label: '돌', value: '돌' },
  { label: '딩고', value: '딩고' },
  { label: '라사압소', value: '라사압소' },
  { label: '래브라도 리트리버', value: '래브라도 리트리버' },
  { label: '레드본 쿤하운드', value: '레드본 쿤하운드' },
  { label: '레온베르거', value: '레온베르거' },
  { label: '레이클랜드 테리어', value: '레이클랜드 테리어' },
  { label: '로다지안 리지백', value: '로다지안 리지백' },
  { label: '로트바일러', value: '로트바일러' },
  { label: '르웰린', value: '르웰린' },
  { label: '말리노이즈', value: '말리노이즈' },
  { label: '말티즈', value: '말티즈' },
  { label: '맬러뮤트', value: '맬러뮤트' },
  { label: '멕시칸 헤어리스 도그', value: '멕시칸 헤어리스 도그' },
  { label: '미니어처 슈나우저', value: '미니어처 슈나우저' },
  { label: '미니어처 푸들', value: '미니어처 푸들' },
  { label: '미니어처 핀셔', value: '미니어처 핀셔' },
  { label: '바센지', value: '바센지' },
  { label: '바셋 하운드', value: '바셋 하운드' },
  { label: '버니즈 마운틴 도그', value: '버니즈 마운틴 도그' },
  { label: '베들링턴 테리어', value: '베들링턴 테리어' },
  { label: '보더 콜리', value: '보더 콜리' },
  { label: '보더 테리어', value: '보더 테리어' },
  { label: '보르조이', value: '보르조이' },
  { label: '보스턴 테리어', value: '보스턴 테리어' },
  { label: '복서', value: '복서' },
  { label: '부비에 데 플랑드르', value: '부비에 데 플랑드르' },
  { label: '불마스티프', value: '불마스티프' },
  { label: '브뤼셀 그리펀', value: '브뤼셀 그리펀' },
  { label: '브리아드', value: '브리아드' },
  { label: '브리트니', value: '브리트니' },
  { label: '블랙 앤 탄 쿤하운드', value: '블랙 앤 탄 쿤하운드' },
  { label: '블러드 하운드', value: '블러드 하운드' },
  { label: '블루틱 쿤하운드', value: '블루틱 쿤하운드' },
  { label: '비글', value: '비글' },
  { label: '비즐라', value: '비즐라' },
  { label: '사모예드견', value: '사모예드견' },
  { label: '살루키', value: '살루키' },
  { label: '서식스 스패니얼', value: '서식스 스패니얼' },
  { label: '세인트버나드', value: '세인트버나드' },
  { label: '셔틀랜드 쉽독', value: '셔틀랜드 쉽독' },
  { label: '스코티시 디어하운드', value: '스코티시 디어하운드' },
  { label: '스코티시 테리어', value: '스코티시 테리어' },
  { label: '스키퍼키', value: '스키퍼키' },
  { label: '스타포드셔 불 테리어', value: '스타포드셔 불 테리어' },
  { label: '스탠다드 푸들', value: '스탠다드 푸들' },
  { label: '스탠더드 슈나우저', value: '스탠더드 슈나우저' },
  { label: '시베리안 허스키', value: '시베리안 허스키' },
  { label: '시츄', value: '시츄' },
  { label: '실리엄 테리어', value: '실리엄 테리어' },
  { label: '아메리칸 스태퍼드셔 테리어', value: '아메리칸 스태퍼드셔 테리어' },
  {
    label: '아이리쉬 소프트코티드 휘튼 테리어',
    value: '아이리쉬 소프트코티드 휘튼 테리어',
  },
  { label: '아이리시 세터', value: '아이리시 세터' },
  { label: '아이리시 울프하운드', value: '아이리시 울프하운드' },
  { label: '아이리시 워터 스패니얼', value: '아이리시 워터 스패니얼' },
  { label: '아이리시 테리어', value: '아이리시 테리어' },
  { label: '아펜젤러 세넨훈드', value: '아펜젤러 세넨훈드' },
  { label: '아펜핀셔', value: '아펜핀셔' },
  { label: '아프간 하운드', value: '아프간 하운드' },
  { label: '아프리카 들개', value: '아프리카 들개' },
  { label: '에스키모 도그', value: '에스키모 도그' },
  { label: '에어데일 테리어', value: '에어데일 테리어' },
  { label: '엔틀버쳐 마운틴 독', value: '엔틀버쳐 마운틴 독' },
  { label: '오스트레일리안 실키 테리어', value: '오스트레일리안 실키 테리어' },
  { label: '오스트레일리안 테리어', value: '오스트레일리안 테리어' },
  { label: '오터 하운드', value: '오터 하운드' },
  { label: '올드 잉글리시 쉽독', value: '올드 잉글리시 쉽독' },
  { label: '와이머라너', value: '와이머라너' },
  { label: '와이어 폭스 테리어', value: '와이어 폭스 테리어' },
  { label: '요크셔 테리어', value: '요크셔 테리어' },
  { label: '워커 쿨하운드', value: '워커 쿨하운드' },
  {
    label: '웨스트 하일랜드 화이트 테리어',
    value: '웨스트 하일랜드 화이트 테리어',
  },
  { label: '웰시 스프링어 스패니얼', value: '웰시 스프링어 스패니얼' },
  { label: '이비전 하운드', value: '이비전 하운드' },
  { label: '이탈리안 그레이하운드', value: '이탈리안 그레이하운드' },
  { label: '잉글리시 스프링어 스패니얼', value: '잉글리시 스프링어 스패니얼' },
  { label: '잉글리시 코커 스패니얼', value: '잉글리시 코커 스패니얼' },
  { label: '잉글리시 폭스하운드', value: '잉글리시 폭스하운드' },
  { label: '자이언트 슈나우저', value: '자이언트 슈나우저' },
  { label: '저먼 셰퍼드', value: '저먼 셰퍼드' },
  { label: '저먼 쇼트헤어드 포인터', value: '저먼 쇼트헤어드 포인터' },
  { label: '차우 차우', value: '차우 차우' },
  { label: '체서피크 베이 리트리버', value: '체서피크 베이 리트리버' },
  { label: '치와와', value: '치와와' },
  { label: '카디컨', value: '카디컨' },
  { label: '컬리 코티드 리트리버', value: '컬리 코티드 리트리버' },
  { label: '케리 블루 테리어', value: '케리 블루 테리어' },
  { label: '케언 테리어', value: '케언 테리어' },
  { label: '켈피', value: '켈피' },
  { label: '코몬돌', value: '코몬돌' },
  { label: '콜리', value: '콜리' },
  { label: '쿠바츠', value: '쿠바츠' },
  { label: '클럼버 스파니엘', value: '클럼버 스파니엘' },
  { label: '키스혼드', value: '키스혼드' },
  { label: '킹 찰스 스패니얼', value: '킹 찰스 스패니얼' },
  { label: '토이 테리어', value: '토이 테리어' },
  { label: '토이푸들', value: '토이푸들' },
  { label: '티베탄 마스티프', value: '티베탄 마스티프' },
  { label: '티베탄 테리어', value: '티베탄 테리어' },
  { label: '파피용', value: '파피용' },
  { label: '퍼그', value: '퍼그' },
  { label: '페키니즈', value: '페키니즈' },
  { label: '펨브로크', value: '펨브로크' },
  { label: '포메라니안', value: '포메라니안' },
  { label: '프렌치 불도그', value: '프렌치 불도그' },
  { label: '플랫 코티드 리트리버', value: '플랫 코티드 리트리버' },
  { label: '휘핏', value: '휘핏' },
];

export const GENDER_LIST = [
  { label: '암컷', value: '암컷' },
  { label: '수컷', value: '수컷' },
  {
    label: '모르겠음',
    value: '모르겠음',
  },
];

export const MAX_IMAGE = 10;
